/**
 * Where the answer applies: five climate zones, twenty regions, 107 provinces.
 *
 * Zones rather than a country field is what makes this extensible. Adding
 * Spain later means adding regions that point at a zone — mostly at zones that
 * already exist — rather than rewriting the model. Nothing in the code branches
 * on country and nothing should start.
 *
 * The province list exists to be picked from, not to be answered at. The data's
 * resolution is the region; a search box accepting any comune would promise a
 * precision the windows have not got, which is the one thing this page cannot
 * afford to do. Codes are the vehicle-plate abbreviations — already unique,
 * already two characters, already what an Italian recognises.
 *
 * Province names are Italian only. Firenze is what is on the road sign and on
 * the shop. Region names carry an English exonym only where one is genuinely in
 * common use; the other ten fall back to the Italian.
 */

import type { Province, Region, Zone } from '../../lib/seasonable';

export const zones: readonly Zone[] = [
  { id: 'alpine', koppen: 'Dfb/Cfb' },
  { id: 'padana', koppen: 'Cfa' },
  { id: 'tyrrhenian', koppen: 'Csa/Csb' },
  { id: 'southern', koppen: 'Csa' },
  { id: 'island', koppen: 'Csa/BSk' },
];

export const regions: readonly Region[] = [
  { id: 'valle-daosta', zone: 'alpine', it: "Valle d'Aosta", en: 'Aosta Valley' },
  { id: 'trentino-alto-adige', zone: 'alpine', it: 'Trentino-Alto Adige' },
  { id: 'piemonte', zone: 'padana', it: 'Piemonte', en: 'Piedmont' },
  { id: 'lombardia', zone: 'padana', it: 'Lombardia', en: 'Lombardy' },
  { id: 'veneto', zone: 'padana', it: 'Veneto' },
  { id: 'friuli-venezia-giulia', zone: 'padana', it: 'Friuli-Venezia Giulia' },
  { id: 'emilia-romagna', zone: 'padana', it: 'Emilia-Romagna' },
  { id: 'liguria', zone: 'tyrrhenian', it: 'Liguria' },
  { id: 'toscana', zone: 'tyrrhenian', it: 'Toscana', en: 'Tuscany' },
  { id: 'umbria', zone: 'tyrrhenian', it: 'Umbria' },
  { id: 'marche', zone: 'tyrrhenian', it: 'Marche' },
  { id: 'lazio', zone: 'tyrrhenian', it: 'Lazio' },
  { id: 'abruzzo', zone: 'southern', it: 'Abruzzo' },
  { id: 'molise', zone: 'southern', it: 'Molise' },
  { id: 'campania', zone: 'southern', it: 'Campania' },
  { id: 'puglia', zone: 'southern', it: 'Puglia', en: 'Apulia' },
  { id: 'basilicata', zone: 'southern', it: 'Basilicata' },
  { id: 'calabria', zone: 'southern', it: 'Calabria' },
  { id: 'sicilia', zone: 'island', it: 'Sicilia', en: 'Sicily' },
  { id: 'sardegna', zone: 'island', it: 'Sardegna', en: 'Sardinia' },
];

const p = (id: string, region: string, name: string): Province => ({ id, region, name });

export const provinces: readonly Province[] = [
  p('to', 'piemonte', 'Torino'),
  p('vc', 'piemonte', 'Vercelli'),
  p('no', 'piemonte', 'Novara'),
  p('cn', 'piemonte', 'Cuneo'),
  p('at', 'piemonte', 'Asti'),
  p('al', 'piemonte', 'Alessandria'),
  p('bi', 'piemonte', 'Biella'),
  p('vb', 'piemonte', 'Verbano-Cusio-Ossola'),
  p('ao', 'valle-daosta', 'Aosta'),
  p('va', 'lombardia', 'Varese'),
  p('co', 'lombardia', 'Como'),
  p('so', 'lombardia', 'Sondrio'),
  p('mi', 'lombardia', 'Milano'),
  p('bg', 'lombardia', 'Bergamo'),
  p('bs', 'lombardia', 'Brescia'),
  p('pv', 'lombardia', 'Pavia'),
  p('cr', 'lombardia', 'Cremona'),
  p('mn', 'lombardia', 'Mantova'),
  p('lc', 'lombardia', 'Lecco'),
  p('lo', 'lombardia', 'Lodi'),
  p('mb', 'lombardia', 'Monza e Brianza'),
  p('bz', 'trentino-alto-adige', 'Bolzano'),
  p('tn', 'trentino-alto-adige', 'Trento'),
  p('vr', 'veneto', 'Verona'),
  p('vi', 'veneto', 'Vicenza'),
  p('bl', 'veneto', 'Belluno'),
  p('tv', 'veneto', 'Treviso'),
  p('ve', 'veneto', 'Venezia'),
  p('pd', 'veneto', 'Padova'),
  p('ro', 'veneto', 'Rovigo'),
  p('ud', 'friuli-venezia-giulia', 'Udine'),
  p('go', 'friuli-venezia-giulia', 'Gorizia'),
  p('ts', 'friuli-venezia-giulia', 'Trieste'),
  p('pn', 'friuli-venezia-giulia', 'Pordenone'),
  p('im', 'liguria', 'Imperia'),
  p('sv', 'liguria', 'Savona'),
  p('ge', 'liguria', 'Genova'),
  p('sp', 'liguria', 'La Spezia'),
  p('pc', 'emilia-romagna', 'Piacenza'),
  p('pr', 'emilia-romagna', 'Parma'),
  p('re', 'emilia-romagna', 'Reggio Emilia'),
  p('mo', 'emilia-romagna', 'Modena'),
  p('bo', 'emilia-romagna', 'Bologna'),
  p('fe', 'emilia-romagna', 'Ferrara'),
  p('ra', 'emilia-romagna', 'Ravenna'),
  p('fc', 'emilia-romagna', 'Forlì-Cesena'),
  p('rn', 'emilia-romagna', 'Rimini'),
  p('ms', 'toscana', 'Massa-Carrara'),
  p('lu', 'toscana', 'Lucca'),
  p('pt', 'toscana', 'Pistoia'),
  p('fi', 'toscana', 'Firenze'),
  p('li', 'toscana', 'Livorno'),
  p('pi', 'toscana', 'Pisa'),
  p('ar', 'toscana', 'Arezzo'),
  p('si', 'toscana', 'Siena'),
  p('gr', 'toscana', 'Grosseto'),
  p('po', 'toscana', 'Prato'),
  p('pg', 'umbria', 'Perugia'),
  p('tr', 'umbria', 'Terni'),
  p('pu', 'marche', 'Pesaro e Urbino'),
  p('an', 'marche', 'Ancona'),
  p('mc', 'marche', 'Macerata'),
  p('ap', 'marche', 'Ascoli Piceno'),
  p('fm', 'marche', 'Fermo'),
  p('vt', 'lazio', 'Viterbo'),
  p('ri', 'lazio', 'Rieti'),
  p('rm', 'lazio', 'Roma'),
  p('lt', 'lazio', 'Latina'),
  p('fr', 'lazio', 'Frosinone'),
  p('aq', 'abruzzo', "L'Aquila"),
  p('te', 'abruzzo', 'Teramo'),
  p('pe', 'abruzzo', 'Pescara'),
  p('ch', 'abruzzo', 'Chieti'),
  p('cb', 'molise', 'Campobasso'),
  p('is', 'molise', 'Isernia'),
  p('ce', 'campania', 'Caserta'),
  p('bn', 'campania', 'Benevento'),
  p('na', 'campania', 'Napoli'),
  p('av', 'campania', 'Avellino'),
  p('sa', 'campania', 'Salerno'),
  p('fg', 'puglia', 'Foggia'),
  p('ba', 'puglia', 'Bari'),
  p('ta', 'puglia', 'Taranto'),
  p('br', 'puglia', 'Brindisi'),
  p('le', 'puglia', 'Lecce'),
  p('bt', 'puglia', 'Barletta-Andria-Trani'),
  p('pz', 'basilicata', 'Potenza'),
  p('mt', 'basilicata', 'Matera'),
  p('cs', 'calabria', 'Cosenza'),
  p('cz', 'calabria', 'Catanzaro'),
  p('rc', 'calabria', 'Reggio Calabria'),
  p('kr', 'calabria', 'Crotone'),
  p('vv', 'calabria', 'Vibo Valentia'),
  p('tp', 'sicilia', 'Trapani'),
  p('pa', 'sicilia', 'Palermo'),
  p('me', 'sicilia', 'Messina'),
  p('ag', 'sicilia', 'Agrigento'),
  p('cl', 'sicilia', 'Caltanissetta'),
  p('en', 'sicilia', 'Enna'),
  p('ct', 'sicilia', 'Catania'),
  p('rg', 'sicilia', 'Ragusa'),
  p('sr', 'sicilia', 'Siracusa'),
  p('ss', 'sardegna', 'Sassari'),
  p('nu', 'sardegna', 'Nuoro'),
  p('ca', 'sardegna', 'Cagliari'),
  p('or', 'sardegna', 'Oristano'),
  p('su', 'sardegna', 'Sud Sardegna'),
];
