/**
 * The catalogue: 65 protected designations and 263 traditional products whose
 * own document states when they are picked.
 *
 * Why designations and not "apple, pear, orange". A disciplinare fixes the
 * harvest window for *its* product in *its* comuni. It is evidence about the
 * Carciofo di Paestum; it is not evidence about artichokes in Salerno, and
 * treating it as such would be the same borrowed authority this page exists to
 * refuse. So the row names what the document names.
 *
 * The catalogue is therefore short, and it is short in a specific way: a
 * designation is here only if its disciplinare states BOTH ends of a window.
 * A great many state only a start ("a partire dal 10 ottobre" for Radicchio
 * Rosso di Treviso) or only an end, and those are not windows. The ones that
 * were checked and dropped are listed in `.pipeline/seasonable/sources-ledger.md`
 * so the next pass does not re-check them.
 *
 * `en` and `it` are the kind of thing it is, used for grouping and for the
 * English reader. The designation itself is a proper noun and is not translated.
 */

import type { Produce } from '../../lib/seasonable';

const fruit = (id: string, name: string, designation: 'DOP' | 'IGP', en: string, it: string): Produce =>
  ({ id, name, designation, category: 'fruit', en, it });

/**
 * A species rather than a designation: no DOP or IGP, because nobody protects
 * "cherry". These exist only to carry the generalised tier, and `designation:
 * null` is what makes them render without a suffix.
 */
const species = (id: string, name: string, category: Produce['category'], en: string, it: string): Produce =>
  ({ id, name, designation: null, category, en, it });

const veg = (id: string, name: string, designation: 'DOP' | 'IGP', en: string, it: string): Produce =>
  ({ id, name, designation, category: 'vegetable', en, it });

/**
 * A *prodotto agroalimentare tradizionale*: on a Region's own list under
 * D.Lgs. 173/1998, with a scheda identificativa the Region publishes.
 *
 * Weaker than a DOP or an IGP, and the row says `PAT` so the reader can weigh
 * it. It is here because the protected-designation register ran out: it names
 * no product at all in Valle d'Aosta, and these two schede state a harvest
 * window for the whole region. `.pipeline/seasonable/enrich/` holds the sweep
 * that found them.
 */
const pat = (id: string, name: string, category: Produce['category'], en: string, it: string): Produce =>
  ({ id, name, designation: 'PAT', category, en, it });

export const produce: readonly Produce[] = [
  // ── Fruit ────────────────────────────────────────────────────────────────
  fruit('amarene-modena', 'Amarene Brusche di Modena', 'IGP', 'sour cherry', 'amarena'),
  fruit('castagna-cuneo', 'Castagna Cuneo', 'IGP', 'chestnut', 'castagna'),
  fruit('castagna-monte-amiata', 'Castagna del Monte Amiata', 'IGP', 'chestnut', 'castagna'),
  fruit('castagna-vallerano', 'Castagna di Vallerano', 'DOP', 'chestnut', 'castagna'),
  fruit('cedro-santa-maria', 'Cedro di Santa Maria del Cedro', 'DOP', 'citron', 'cedro'),
  fruit('ciliegia-bracigliano', 'Ciliegia di Bracigliano', 'IGP', 'cherry', 'ciliegia'),
  fruit('ciliegia-lari', 'Ciliegia di Lari', 'IGP', 'cherry', 'ciliegia'),
  fruit('ciliegia-vignola', 'Ciliegia di Vignola', 'IGP', 'cherry', 'ciliegia'),
  fruit('farina-lunigiana', 'Farina di Castagne della Lunigiana', 'DOP', 'chestnut', 'castagna'),
  fruit('farina-neccio', 'Farina di Neccio della Garfagnana', 'DOP', 'chestnut', 'castagna'),
  fruit('fichi-cosenza', 'Fichi di Cosenza', 'DOP', 'fig', 'fico'),
  fruit('ficodindia-etna', "Ficodindia dell'Etna", 'DOP', 'prickly pear', 'ficodindia'),
  fruit('ficodindia-san-cono', 'Ficodindia di San Cono', 'DOP', 'prickly pear', 'ficodindia'),
  fruit('fragola-basilicata', 'Fragola della Basilicata', 'IGP', 'strawberry', 'fragola'),
  fruit('kiwi-latina', 'Kiwi Latina', 'IGP', 'kiwi', 'kiwi'),
  fruit('limone-costa-amalfi', "Limone Costa d'Amalfi", 'IGP', 'lemon', 'limone'),
  fruit('limone-interdonato', 'Limone Interdonato Messina', 'IGP', 'lemon', 'limone'),
  fruit('limone-sorrento', 'Limone di Sorrento', 'IGP', 'lemon', 'limone'),
  fruit('marrone-combai', 'Marrone di Combai', 'IGP', 'chestnut', 'castagna'),
  fruit('marrone-serino', 'Marrone di Serino', 'IGP', 'chestnut', 'castagna'),
  fruit('marroni-monfenera', 'Marroni del Monfenera', 'IGP', 'chestnut', 'castagna'),
  fruit('marrone-valle-susa', 'Marrone della Valle di Susa', 'IGP', 'chestnut', 'castagna'),
  fruit('mela-rossa-cuneo', 'Mela Rossa Cuneo', 'IGP', 'apple', 'mela'),
  fruit('mele-trentino', 'Mele del Trentino', 'IGP', 'apple', 'mela'),
  // The only two products of any register in Valle d'Aosta, and both are apples.
  pat('golden-valle-aosta', "Golden delicious della Valle d'Aosta", 'fruit', 'apple', 'mela'),
  pat('renetta-valle-aosta', "Renetta della Valle d'Aosta", 'fruit', 'apple', 'mela'),
  fruit('mela-val-di-non', 'Mela Val di Non', 'DOP', 'apple', 'mela'),
  fruit('oliva-ascolana', 'Oliva Ascolana del Piceno', 'DOP', 'olive', 'oliva'),
  fruit('pera-emilia-romagna', "Pera dell'Emilia Romagna", 'IGP', 'pear', 'pera'),
  fruit('pesca-delia', 'Pesca di Delia', 'IGP', 'peach', 'pesca'),
  fruit('pesca-leonforte', 'Pesca di Leonforte', 'IGP', 'peach', 'pesca'),
  fruit('pescabivona', 'Pescabivona', 'IGP', 'peach', 'pesca'),
  fruit('susina-dro', 'Susina di Dro', 'DOP', 'plum', 'susina'),
  fruit('arancia-gargano', 'Arancia del Gargano', 'IGP', 'orange', 'arancia'),
  fruit('arancia-ribera', 'Arancia di Ribera', 'DOP', 'orange', 'arancia'),
  species('cherry-generic', 'Cherry', 'fruit', 'cherry', 'ciliegia'),
  species('chestnut-generic', 'Chestnut', 'fruit', 'chestnut', 'castagna'),

  // ── PAT: fruit from the regional registers ───────────────────────────────
  // Sicilia's schede, Lazio's ARSIAL guide, Friuli's Cibario, Sardegna's and
  // Marche's lists. A PAT is a lighter instrument than a DOP or an IGP and the
  // suffix says so; what it shares with a disciplinare is a published document
  // naming the territory and the picking.
  pat('albicocco-scillato', 'Albicocco di Scillato', 'fruit', 'apricot', 'albicocca'),
  pat('arancia-scillato', 'Arancia Biondo di Scillato', 'fruit', 'orange', 'arancia'),
  pat('arancio-fondi', 'Arancio Biondo di Fondi', 'fruit', 'orange', 'arancia'),
  pat('castagna-terelle', 'Castagna di Terelle', 'fruit', 'chestnut', 'castagna'),
  pat('ciliegia-barracocca', 'Ciliegia Barracocca di Villacidro', 'fruit', 'cherry', 'ciliegia'),
  pat('ciliegia-mastrantoni', 'Ciliegia Mastrantoni', 'fruit', 'cherry', 'ciliegia'),
  pat('ficodindia-valle-torto', 'Ficodindia della Valle del Torto', 'fruit', 'prickly pear', 'ficodindia'),
  pat('figo-moro', 'Figo moro da Caneva', 'fruit', 'fig', 'fico'),
  pat('fragola-maletto', 'Fragola di Maletto', 'fruit', 'strawberry', 'fragola'),
  pat('fragolina-nemi', 'Fragolina di Nemi', 'fruit', 'strawberry', 'fragola'),
  pat('fragolina-ribera', 'Fragolina di Ribera', 'fruit', 'strawberry', 'fragola'),
  pat('marrone-acquasanta', 'Marrone di Acquasanta Terme', 'fruit', 'chestnut', 'castagna'),
  pat('marrone-antrodocano', 'Marrone Antrodocano', 'fruit', 'chestnut', 'castagna'),
  pat('marrone-cimini', 'Marrone dei Monti Cimini', 'fruit', 'chestnut', 'castagna'),
  pat('marrone-latera', 'Marrone di Latera', 'fruit', 'chestnut', 'castagna'),
  pat('marrone-segnino', 'Marrone Segnino', 'fruit', 'chestnut', 'castagna'),
  pat('mele-cola', 'Mele Cola', 'fruit', 'apple', 'mela'),
  pat('oliva-buccheri', 'Oliva nera di Buccheri', 'fruit', 'olive', 'oliva'),
  pat('oliva-nebba', 'Oliva Nebba', 'fruit', 'olive', 'oliva'),
  pat('ovaletto-calatafimi', 'Ovaletto di Calatafimi', 'fruit', 'orange', 'arancia'),
  pat('pera-butirra', "Pere Butirra d'estate", 'fruit', 'pear', 'pera'),
  pat('pera-per-martin', 'Pera Pêr Martìn', 'fruit', 'pear', 'pera'),
  pat('pera-virgolosa', 'Pere Virgolosa', 'fruit', 'pear', 'pera'),
  pat('prugna-picinisco', 'Prugna Pizzutella di Picinisco', 'fruit', 'plum', 'prugna'),
  pat('visciole-sole', 'Visciole sciolte al sole', 'fruit', 'sour cherry', 'visciola'),

  // ── Vegetables ───────────────────────────────────────────────────────────
  veg('aglio-voghiera', 'Aglio di Voghiera', 'DOP', 'garlic', 'aglio'),
  veg('asparago-badoere', 'Asparago di Badoere', 'IGP', 'asparagus', 'asparago'),
  veg('asparago-bassano', 'Asparago Bianco di Bassano', 'DOP', 'asparagus', 'asparago'),
  veg('asparago-canino', 'Asparago Verde di Canino', 'IGP', 'asparagus', 'asparago'),
  veg('asparago-cantello', 'Asparago di Cantello', 'IGP', 'asparagus', 'asparago'),
  veg('asparago-cimadolmo', 'Asparago Bianco di Cimadolmo', 'IGP', 'asparagus', 'asparago'),
  veg('cappero-eolie', 'Cappero delle Isole Eolie', 'DOP', 'caper', 'cappero'),
  veg('cappero-pantelleria', 'Cappero di Pantelleria', 'IGP', 'caper', 'cappero'),
  veg('basilico-genovese', 'Basilico Genovese', 'DOP', 'basil', 'basilico'),
  veg('brovada', 'Brovada', 'DOP', 'turnip', 'rapa'),
  veg('carciofo-brindisino', 'Carciofo Brindisino', 'IGP', 'artichoke', 'carciofo'),
  veg('carciofo-paestum', 'Carciofo di Paestum', 'IGP', 'artichoke', 'carciofo'),
  veg('carciofo-romanesco', 'Carciofo Romanesco del Lazio', 'IGP', 'artichoke', 'carciofo'),
  veg('carciofo-sardegna', 'Carciofo Spinoso di Sardegna', 'DOP', 'artichoke', 'carciofo'),
  veg('carota-ispica', 'Carota Novella di Ispica', 'IGP', 'carrot', 'carota'),
  veg('fagioli-rotonda', 'Fagioli Bianchi di Rotonda', 'DOP', 'bean', 'fagiolo'),
  veg('fagiolo-atina', 'Fagiolo Cannellino di Atina', 'DOP', 'bean', 'fagiolo'),
  veg('fagiolo-cuneo', 'Fagiolo Cuneo', 'IGP', 'bean', 'fagiolo'),
  veg('finocchio-capo-rizzuto', 'Finocchio di Isola Capo Rizzuto', 'IGP', 'fennel', 'finocchio'),
  veg('fungo-borgotaro', 'Fungo di Borgotaro', 'IGP', 'mushroom', 'fungo'),
  veg('lenticchia-onano', 'Lenticchia di Onano', 'IGP', 'lentil', 'lenticchia'),
  veg('melanzana-rotonda', 'Melanzana Rossa di Rotonda', 'DOP', 'aubergine', 'melanzana'),
  veg('patata-alto-viterbese', "Patata dell'Alto Viterbese", 'IGP', 'potato', 'patata'),
  veg('patata-colfiorito', 'Patata Rossa di Colfiorito', 'IGP', 'potato', 'patata'),
  veg('patata-fucino', 'Patata del Fucino', 'IGP', 'potato', 'patata'),
  veg('patata-galatina', 'Patata Novella di Galatina', 'DOP', 'potato', 'patata'),
  veg('patata-sila', 'Patata della Sila', 'IGP', 'potato', 'patata'),
  veg('peperoncino-calabria', 'Peperoncino di Calabria', 'IGP', 'chilli', 'peperoncino'),
  veg('peperone-pontecorvo', 'Peperone di Pontecorvo', 'DOP', 'pepper', 'peperone'),
  veg('piennolo-vesuvio', 'Pomodorino del Piennolo del Vesuvio', 'DOP', 'tomato', 'pomodoro'),
  veg('radicchio-chioggia', 'Radicchio di Chioggia', 'IGP', 'chicory', 'radicchio'),
  veg('san-marzano', "Pomodoro San Marzano dell'Agro Sarnese-Nocerino", 'DOP', 'tomato', 'pomodoro'),

  // ── PAT: Abruzzo, the Region's atlas ─────────────────────────────────────
  pat('aglio-sulmona', 'Aglio rosso di Sulmona', 'vegetable', 'garlic', 'aglio'),
  pat('carciofo-vastese', 'Carciofo del Vastese', 'vegetable', 'artichoke', 'carciofo'),
  pat('peperone-altino', 'Peperone rosso di Altino', 'vegetable', 'pepper', 'peperone'),
  // ── PAT: Puglia ──────────────────────────────────────────────
  pat('pug-albicocca-di-galatone', 'Albicocca di Galatone', 'fruit', 'apricot', 'albicocca'),
  pat('pug-batata-dell-agro-leccese', "Batata dell'agro leccese", 'vegetable', 'sweet potato', 'batata'),
  pat('pug-carciofo-di-san-ferdinando-di-', 'Carciofo di San Ferdinando di Puglia', 'vegetable', 'artichoke', 'carciofo'),
  pat('pug-carosello-di-manduria', 'Carosello di Manduria', 'fruit', 'melon', 'melone'),
  pat('pug-carota-di-polignano', 'Carota di Polignano', 'vegetable', 'carrot', 'carota'),
  pat('pug-cicoria-all-acqua', "Cicoria all'acqua", 'vegetable', 'chicory', 'cicoria'),
  pat('pug-cicoria-riccia', 'Cicoria riccia', 'vegetable', 'chicory', 'cicoria'),
  pat('pug-cicoria-puntarelle-molfettese', 'Cicoria “puntarelle” molfettese', 'vegetable', 'chicory', 'cicoria'),
  pat('pug-ciliegie-di-puglia', 'Ciliegie di Puglia', 'fruit', 'cherry', 'ciliegia'),
  pat('pug-cima-di-rapa-di-minervino', 'Cima di rapa di Minervino', 'vegetable', 'turnip', 'cima di rapa'),
  pat('pug-cima-di-zucchina', 'Cima di zucchina', 'vegetable', 'courgette', 'zucchina'),
  pat('pug-cipolla-di-acquaviva-delle-fon', 'Cipolla di Acquaviva delle Fonti', 'vegetable', 'onion', 'cipolla'),
  pat('pug-cipolla-di-zapponeta', 'Cipolla di Zapponeta', 'vegetable', 'onion', 'cipolla'),
  pat('pug-fave-fresche', 'Fave fresche', 'vegetable', 'broad bean', 'fava'),
  pat('pug-fiorone-di-torre-canne', 'Fiorone di Torre Canne', 'fruit', 'fig', 'fico'),
  pat('pug-mela-limoncella-dei-monti-daun', 'Mela limoncella dei Monti Dauni meridionali', 'fruit', 'apple', 'mela'),
  pat('pug-meloncella', 'Meloncella', 'fruit', 'melon', 'melone'),
  pat('pug-mugnuli', 'Mùgnuli', 'vegetable', 'broccoli', 'mugnolo'),
  pat('pug-patata-bisestile', 'Patata bisestile', 'vegetable', 'potato', 'patata'),
  pat('pug-patata-di-zapponeta', 'Patata di Zapponeta', 'vegetable', 'potato', 'patata'),
  pat('pug-patata-zuccherina-di-calimera', 'Patata zuccherina di Calimera', 'vegetable', 'sweet potato', 'batata'),
  pat('pug-pera-petrucina', 'Pera Petrucina', 'fruit', 'pear', 'pera'),
  pat('pug-percoca-di-loconia', 'Percoca di Loconia', 'fruit', 'peach', 'pesca'),
  pat('pug-piattello', 'Piattello', 'fruit', 'orange', 'arancia'),
  pat('pug-pisello-riccio-di-sannicola', 'Pisello riccio di Sannicola', 'vegetable', 'pea', 'pisello'),
  pat('pug-pomodorino-di-manduria', 'Pomodorino di Manduria', 'vegetable', 'tomato', 'pomodoro'),
  pat('pug-pomodoro-da-serbo-giallo', 'Pomodoro da serbo giallo', 'vegetable', 'tomato', 'pomodoro'),
  pat('pug-sedano-di-torrepaduli', 'Sedano di Torrepaduli', 'vegetable', 'celery', 'sedano'),
  pat('pug-sponzali', 'Sponzali', 'vegetable', 'onion', 'cipollotto'),
  pat('pug-tortarello', 'Tortarello', 'fruit', 'melon', 'melone'),
  pat('pug-uva-baresana', 'Uva baresana', 'fruit', 'grape', 'uva'),
  pat('pug-uva-da-tavola', 'Uva da tavola', 'fruit', 'grape', 'uva'),
  // ── PAT: Liguria ──────────────────────────────────────────────
  pat('lig-carciofo-di-pompeiana', 'Carciofo di Pompeiana', 'vegetable', 'artichoke', 'carciofo'),
  pat('lig-ciliegia-di-castelbianco', 'Ciliegia di Castelbianco', 'fruit', 'cherry', 'ciliegia'),
  pat('lig-zucca-di-rocchetta-cengio', 'Zucca di Rocchetta Cengio', 'vegetable', 'pumpkin', 'zucca'),
  // ── PAT: Piemonte ──────────────────────────────────────────────
  pat('pie-aglio-di-molino-dei-torti', 'Aglio di Molino dei Torti', 'vegetable', 'garlic', 'aglio'),
  pat('pie-albicocca-tonda-di-costigliole', 'Albicocca tonda di Costigliole', 'fruit', 'apricot', 'albicocca'),
  pat('pie-asparago-santenese', 'Asparago santenese', 'vegetable', 'asparagus', 'asparago'),
  pat('pie-bietola-a-costa-rossa-astigian', 'Bietola a costa rossa astigiana', 'vegetable', 'chard', 'bietola'),
  pat('pie-bietola-rossa-di-castellazzo-b', 'Bietola rossa di Castellazzo Bormida', 'vegetable', 'chard', 'bietola'),
  pat('pie-carota-di-san-rocco-castagnare', 'Carota di San Rocco Castagnaretta', 'vegetable', 'carrot', 'carota'),
  pat('pie-cicoria-pan-di-zucchero-casale', 'Cicoria pan di zucchero casalese', 'vegetable', 'chicory', 'cicoria'),
  pat('pie-cipolla-dorata-di-castelnuovo-', 'Cipolla dorata di Castelnuovo Scrivia', 'vegetable', 'onion', 'cipolla'),
  pat('pie-cipolla-piatlina-bionda-di-and', 'Cipolla piatlina bionda di Andezeno', 'vegetable', 'onion', 'cipolla'),
  pat('pie-cipolla-rossa-di-castelnuovo-s', 'Cipolla rossa di Castelnuovo Scrivia', 'vegetable', 'onion', 'cipolla'),
  pat('pie-fragola-profumata-di-tortona', 'Fragola profumata di Tortona', 'fruit', 'strawberry', 'fragola'),
  pat('pie-fragolina-di-san-mauro-torines', 'Fragolina di San Mauro Torinese', 'fruit', 'strawberry', 'fragola'),
  pat('pie-melanzana-violetta-casalese', 'Melanzana violetta casalese', 'vegetable', 'aubergine', 'melanzana'),
  pat('pie-mele-del-piemonte', 'Mele del Piemonte', 'fruit', 'apple', 'mela'),
  pat('pie-meloni-di-isola-sant-antonio', "Meloni di Isola Sant'Antonio", 'fruit', 'melon', 'melone'),
  pat('pie-patate-di-entracque', 'Patate di Entracque', 'vegetable', 'potato', 'patata'),
  pat('pie-patate-di-montagna', 'Patate di Montagna', 'vegetable', 'potato', 'patata'),
  pat('pie-pera-madernassa', 'Pera Madernassa', 'fruit', 'pear', 'pera'),
  pat('pie-pere-martin-sec', 'Pere Martin sec', 'fruit', 'pear', 'pera'),
  pat('pie-pere-delle-valli-di-lanzo', 'Pere delle Valli di Lanzo', 'fruit', 'pear', 'pera'),
  pat('pie-pesche-autoctone-del-piemonte', 'Pesche autoctone del Piemonte', 'fruit', 'peach', 'pesca'),
  pat('pie-pisello-di-casalborgone', 'Pisello di Casalborgone', 'vegetable', 'pea', 'pisello'),
  pat('pie-pomodoro-costoluto-di-cambiano', 'Pomodoro costoluto di Cambiano', 'vegetable', 'tomato', 'pomodoro'),
  pat('pie-pomodoro-costoluto-di-chivasso', 'Pomodoro costoluto di Chivasso', 'vegetable', 'tomato', 'pomodoro'),
  pat('pie-rapa-di-caprauna', 'Rapa di Caprauna', 'vegetable', 'turnip', 'rapa'),
  pat('pie-susine-santa-clara-del-saluzze', 'Susine Santa Clara del Saluzzese', 'fruit', 'plum', 'susina'),
  pat('pie-susine-della-collina-torinese', 'Susine della collina torinese', 'fruit', 'plum', 'susina'),
  pat('pie-trifulot-del-bur', 'Trifulot del Bür', 'vegetable', 'potato', 'patata'),
  // ── PAT: Veneto ──────────────────────────────────────────────
  pat('ven-aglio-del-medio-adige', 'Aglio del Medio Adige', 'vegetable', 'garlic', 'aglio'),
  pat('ven-antiche-pesche-di-mogliano-ven', 'Antiche pesche di Mogliano Veneto', 'fruit', 'peach', 'pesca'),
  pat('ven-asparago-di-arcole', 'Asparago di Arcole', 'vegetable', 'asparagus', 'asparago'),
  pat('ven-asparago-di-giare', 'Asparago di Giare', 'vegetable', 'asparagus', 'asparago'),
  pat('ven-asparago-di-mambrotta', 'Asparago di Mambrotta', 'vegetable', 'asparagus', 'asparago'),
  pat('ven-asparago-di-padova', 'Asparago di Padova', 'vegetable', 'asparagus', 'asparago'),
  pat('ven-asparago-di-palazzetto', 'Asparago di Palazzetto', 'vegetable', 'asparagus', 'asparago'),
  pat('ven-barbabietola-rossa-di-chioggia', 'Barbabietola rossa di Chioggia', 'vegetable', 'beetroot', 'barbabietola'),
  pat('ven-bietola-di-bassano', 'Bietola di Bassano', 'vegetable', 'chard', 'bietola'),
  pat('ven-bisi-de-lumignan', 'Bisi de Lumignan', 'vegetable', 'pea', 'pisello'),
  pat('ven-bisi-de-peseggia', 'Bisi de Peseggia', 'vegetable', 'pea', 'pisello'),
  pat('ven-broccoletto-di-custoza', 'Broccoletto di Custoza', 'vegetable', 'broccoli', 'broccoletto'),
  pat('ven-broccolo-di-bassano', 'Broccolo di Bassano', 'vegetable', 'broccoli', 'broccolo'),
  pat('ven-broccolo-fiolaro-di-creazzo', 'Broccolo fiolaro di Creazzo', 'vegetable', 'broccoli', 'broccolo'),
  pat('ven-carciofo-violetto-di-sant-eras', "Carciofo violetto di Sant'Erasmo", 'vegetable', 'artichoke', 'carciofo'),
  pat('ven-carota-di-chioggia', 'Carota di Chioggia', 'vegetable', 'carrot', 'carota'),
  pat('ven-cicoria-catalogna-gigante-di-c', 'Cicoria catalogna gigante di Chioggia', 'vegetable', 'chicory', 'cicoria'),
  pat('ven-cipolla-bianca-di-chioggia', 'Cipolla bianca di Chioggia', 'vegetable', 'onion', 'cipolla'),
  pat('ven-cipolla-rosa-di-bassano', 'Cipolla rosa di Bassano', 'vegetable', 'onion', 'cipolla'),
  pat('ven-craut-verde-agre', 'Craut verde agre', 'vegetable', 'cabbage', 'cavolo cappuccio'),
  pat('ven-fagiolino-meraviglia-di-venezi', 'Fagiolino meraviglia di Venezia', 'vegetable', 'bean', 'fagiolo'),
  pat('ven-fagiolo-bonel-di-fonzaso', 'Fagiolo bonèl di Fonzaso', 'vegetable', 'bean', 'fagiolo'),
  pat('ven-fagiolo-borlotto-nano-di-levad', 'Fagiolo borlotto nano di Levada', 'vegetable', 'bean', 'fagiolo'),
  pat('ven-fasola-posenata', 'Fasola posenata', 'vegetable', 'bean', 'fagiolo'),
  pat('ven-fragola-di-verona', 'Fragola di Verona', 'fruit', 'strawberry', 'fragola'),
  pat('ven-germoglio-di-radicchio-bianco-', 'Germoglio di radicchio bianco nostrano di Bassano', 'vegetable', 'chicory', 'radicchio'),
  pat('ven-giuggiola-dei-colli-euganei', 'Giuggiola dei Colli Euganei', 'fruit', 'jujube', 'giuggiola'),
  pat('ven-giuggiolo-del-cavallino', 'Giuggiolo del Cavallino', 'fruit', 'jujube', 'giuggiola'),
  pat('ven-marroni-di-valrovina', 'Marroni di Valrovina', 'fruit', 'chestnut', 'castagna'),
  pat('ven-patata-americana-di-zero-branc', 'Patata americana di Zero Branco', 'vegetable', 'sweet potato', 'patata americana'),
  pat('ven-patata-di-bolca', 'Patata di Bolca', 'vegetable', 'potato', 'patata'),
  pat('ven-patata-di-rotzo', 'Patata di Rotzo', 'vegetable', 'potato', 'patata'),
  pat('ven-peperone-di-zero-branco', 'Peperone di Zero Branco', 'vegetable', 'pepper', 'peperone'),
  pat('ven-radicchio-bianco-o-variegato-d', 'Radicchio bianco o variegato di Lusia', 'vegetable', 'chicory', 'radicchio'),
  pat('ven-radicchio-variegato-bianco-di-', 'Radicchio variegato bianco di Bassano', 'vegetable', 'chicory', 'radicchio'),
  pat('ven-radicio-verdon-da-cortel', 'Radicio verdòn da cortèl', 'vegetable', 'chicory', 'radicchio'),
  pat('ven-sedano-rapa-di-ronco-all-adige', "Sedano rapa di Ronco all'Adige", 'vegetable', 'celery', 'sedano'),
  pat('ven-verza-moretta-di-veronella', 'Verza moretta di Veronella', 'vegetable', 'cabbage', 'verza'),
  pat('ven-zucca-marina-di-chioggia', 'Zucca marina di Chioggia', 'vegetable', 'pumpkin', 'zucca'),
  pat('ven-zucca-santa-bellunese', 'Zucca santa bellunese', 'vegetable', 'pumpkin', 'zucca'),
  // ── PAT: Umbria, one scheda per product ──────────────────────────────────
  pat('umb-cipolla-cannara', 'Cipolla di Cannara', 'vegetable', 'onion', 'cipolla'),
  pat('umb-marrone', 'Marrone', 'fruit', 'chestnut', 'castagna'),
  pat('umb-sedano-nero-trevi', 'Sedano nero di Trevi', 'vegetable', 'celery', 'sedano'),
  // ── PAT: Campania, one page per product ──────────────────────────────────
  pat('cam-aglio-dell-ufita', "Aglio dell'Ufita", 'vegetable', 'garlic', 'aglio'),
  pat('cam-broccolo-san-pasquale', 'Broccolo San Pasquale', 'vegetable', 'broccoli', 'broccolo'),
  pat('cam-carciofo-capuanella', 'Carciofo capuanella', 'vegetable', 'artichoke', 'carciofo'),
  pat('cam-carciofo-di-castellammare', 'Carciofo di Castellammare', 'vegetable', 'artichoke', 'carciofo'),
  pat('cam-carciofo-pignatella-carciofo-ros', 'Carciofo pignatella, carciofo rosso, carciofolla pascaiola', 'vegetable', 'artichoke', 'carciofo'),
  pat('cam-castagna-del-monte-faito', 'Castagna del Monte Faito', 'fruit', 'chestnut', 'castagna'),
  pat('cam-castagna-di-acerno', 'Castagna di Acerno', 'fruit', 'chestnut', 'castagna'),
  pat('cam-castagna-di-trevico', 'Castagna di Trevico', 'fruit', 'chestnut', 'castagna'),
  pat('cam-castagna-jonna-di-civitella-lici', 'Castagna jonna di Civitella Licinio', 'fruit', 'chestnut', 'castagna'),
  pat('cam-castagna-o-marrone-del-partenio', 'Castagna o marrone del Partenio', 'fruit', 'chestnut', 'castagna'),
  pat('cam-ciliegia-del-monte-e-ciliegia-de', 'Ciliegia del Monte e ciliegia della Recca', 'fruit', 'cherry', 'ciliegia'),
  pat('cam-ciliegia-di-pimonte', 'Ciliegia di Pimonte', 'fruit', 'cherry', 'ciliegia'),
  pat('cam-ciliegia-di-siano', 'Ciliegia di Siano', 'fruit', 'cherry', 'ciliegia'),
  pat('cam-cipolla-alifana', 'Cipolla alifana', 'vegetable', 'onion', 'cipolla'),
  pat('cam-cipolla-bianca-di-pompei', 'Cipolla bianca di Pompei', 'vegetable', 'onion', 'cipolla'),
  pat('cam-cipolla-di-airola', 'Cipolla di Airola', 'vegetable', 'onion', 'cipolla'),
  pat('cam-fagiolo-mustacciello', 'Fagiolo mustacciello', 'vegetable', 'bean', 'fagiolo'),
  pat('cam-finocchio-bianco-palettone', 'Finocchio bianco palettone', 'vegetable', 'fennel', 'finocchio'),
  pat('cam-finocchio-di-sarno', 'Finocchio di Sarno', 'vegetable', 'fennel', 'finocchio'),
  pat('cam-giallona-di-siano', 'Giallona di Siano', 'fruit', 'peach', 'pesca'),
  pat('cam-melone-napoletano', 'Melone napoletano', 'fruit', 'melon', 'melone'),
  pat('cam-oliva-marinese', 'Oliva marinese', 'fruit', 'olive', 'oliva'),
  pat('cam-patata-di-monte-s-giacomo', 'Patata di Monte S. Giacomo', 'vegetable', 'potato', 'patata'),
  pat('cam-patata-di-trevico', 'Patata di Trevico', 'vegetable', 'potato', 'patata'),
  pat('cam-patata-fresca-campana', 'Patata fresca campana', 'vegetable', 'potato', 'patata'),
  pat('cam-patata-nera-del-matese', 'Patata nera del Matese', 'vegetable', 'potato', 'patata'),
  pat('cam-patata-rossa-del-vallo-di-diano', 'Patata rossa del Vallo di Diano', 'vegetable', 'potato', 'patata'),
  pat('cam-peperoncini-verdi-o-di-fiume', 'Peperoncini verdi o di fiume', 'vegetable', 'chilli', 'peperoncino'),
  pat('cam-peperone-cazzone', 'Peperone cazzone', 'vegetable', 'pepper', 'peperone'),
  pat('cam-peperone-sassaniello', 'Peperone sassaniello', 'vegetable', 'pepper', 'peperone'),
  pat('cam-pera-lardara', 'Pera lardara', 'fruit', 'pear', 'pera'),
  pat('cam-pisello-centogiorni', 'Pisello centogiorni', 'vegetable', 'pea', 'pisello'),
  pat('cam-pomodorino-campano', 'Pomodorino campano', 'vegetable', 'tomato', 'pomodoro'),
  pat('cam-pomodorino-cannellino-di-pimonte', 'Pomodorino cannellino di Pimonte', 'vegetable', 'tomato', 'pomodoro'),
  pat('cam-pomodorino-dell-ufita', "Pomodorino dell'Ufita", 'vegetable', 'tomato', 'pomodoro'),
  pat('cam-pomodoro-cannellino-flegreo', 'Pomodoro cannellino flegreo', 'vegetable', 'tomato', 'pomodoro'),
  pat('cam-pomodoro-fiaschello-di-battipagl', 'Pomodoro fiaschello di Battipaglia', 'vegetable', 'tomato', 'pomodoro'),
  pat('cam-rapa-catozza', 'Rapa catozza', 'vegetable', 'turnip', 'rapa'),
  pat('cam-sedano-di-gesualdo', 'Sedano di Gesualdo', 'vegetable', 'celery', 'sedano'),
  pat('cam-zucchino-san-pasquale', 'Zucchino San Pasquale', 'vegetable', 'courgette', 'zucchina'),
  // ── PAT: Toscana, one scheda per product ─────────────────────────────────
  // The Region publishes 195 vegetable schede, one web page each, and 60 of
  // them state both ends of a window. Each row cites its own scheda.
  pat('tos-aglio-massese', 'Aglio massese', 'vegetable', 'garlic', 'aglio'),
  pat('tos-aglione-della-valdichiana', 'Aglione della Valdichiana', 'vegetable', 'garlic', 'aglio'),
  pat('tos-arancio-massese', 'Arancio massese', 'fruit', 'orange', 'arancia'),
  pat('tos-barba-massese', 'Barba massese', 'vegetable', 'salsify', 'scorzobianca'),
  pat('tos-carciofo-di-chiusure', 'Carciofo di Chiusure', 'vegetable', 'artichoke', 'carciofo'),
  pat('tos-carciofo-di-san-miniato', 'Carciofo di San Miniato', 'vegetable', 'artichoke', 'carciofo'),
  pat('tos-carciofo-empolese', 'Carciofo empolese', 'vegetable', 'artichoke', 'carciofo'),
  pat('tos-cardo-della-val-di-cornia', 'Cardo della Val di Cornia', 'vegetable', 'cardoon', 'cardo'),
  pat('tos-cardo-massese', 'Cardo massese', 'vegetable', 'cardoon', 'cardo'),
  pat('tos-castagna-pistolesa', 'Castagna pistolesa', 'fruit', 'chestnut', 'castagna'),
  pat('tos-cavolfiore-fiorentino-tardivo', 'Cavolfiore fiorentino tardivo', 'vegetable', 'cauliflower', 'cavolfiore'),
  pat('tos-cavolfiore-precoce-toscano', 'Cavolfiore precoce toscano', 'vegetable', 'cauliflower', 'cavolfiore'),
  pat('tos-cipolla-di-bassone', 'Cipolla di Bassone', 'vegetable', 'onion', 'cipolla'),
  pat('tos-cipolla-di-certaldo', 'Cipolla di Certaldo', 'vegetable', 'onion', 'cipolla'),
  pat('tos-cipolla-di-ripola', 'Cipolla di Ripola', 'vegetable', 'onion', 'cipolla'),
  pat('tos-cipolla-di-terceretoli', 'Cipolla di Terceretoli', 'vegetable', 'onion', 'cipolla'),
  pat('tos-cipolla-massese', 'Cipolla massese', 'vegetable', 'onion', 'cipolla'),
  pat('tos-cipolla-rossa-della-valtiberina', 'Cipolla rossa della Valtiberina', 'vegetable', 'onion', 'cipolla'),
  pat('tos-cipolla-vernina', 'Cipolla vernina', 'vegetable', 'onion', 'cipolla'),
  pat('tos-cocomero-gigante', 'Cocomero gigante', 'fruit', 'watermelon', 'cocomero'),
  pat('tos-fagiolo-marconi-a-seme-nero', 'Fagiolo Marconi a seme nero', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-borlotto-di-maremma', 'Fagiolo borlotto di Maremma', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-borlotto-nano-di-sorano', 'Fagiolo borlotto nano di Sorano', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-cannellino', 'Fagiolo cannellino', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-dall-occhio-del-valdarno', "Fagiolo dall'occhio del Valdarno", 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-di-zeri', 'Fagiolo di Zeri', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-fico-di-gallicano', 'Fagiolo fico di Gallicano', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-malato', 'Fagiolo malato', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-mascherino', 'Fagiolo mascherino', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-scritto-della-garfagnana', 'Fagiolo scritto della Garfagnana', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-serpente-toscano', 'Fagiolo serpente toscano', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fagiolo-turco-di-castello', 'Fagiolo turco di Castello', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-fico-san-piero', 'Fico San Piero', 'fruit', 'fig', 'fico'),
  pat('tos-mela-rosa-del-casentino', 'Mela rosa del Casentino', 'fruit', 'apple', 'mela'),
  pat('tos-mela-stayman-aretina', 'Mela stayman aretina', 'fruit', 'apple', 'mela'),
  pat('tos-melograno-di-firenze', 'Melograno di Firenze', 'fruit', 'pomegranate', 'melograno'),
  pat('tos-melone-della-val-di-cornia', 'Melone della Val di Cornia', 'fruit', 'melon', 'melone'),
  pat('tos-patata-di-santa-maria-a-monte', 'Patata di Santa Maria a Monte', 'vegetable', 'potato', 'patata'),
  pat('tos-pera-coscia-di-firenze', 'Pera coscia di Firenze', 'fruit', 'pear', 'pera'),
  pat('tos-pera-gentile', 'Pera gentile', 'fruit', 'pear', 'pera'),
  pat('tos-pesca-michelini', 'Pesca Michelini', 'fruit', 'peach', 'pesca'),
  pat('tos-pesca-maglia-rosa', 'Pesca maglia rosa', 'fruit', 'peach', 'pesca'),
  pat('tos-pesca-mora-di-moriano-dolfi', 'Pesca mora di Moriano Dolfi', 'fruit', 'peach', 'pesca'),
  pat('tos-pesca-regina-di-londa', 'Pesca regina di Londa', 'fruit', 'peach', 'pesca'),
  pat('tos-peschetti-di-candia', 'Peschetti di Candia', 'fruit', 'peach', 'pesca'),
  pat('tos-piattella-pisana', 'Piattella pisana', 'vegetable', 'bean', 'fagiolo'),
  pat('tos-pisello-a-mezza-frasca-aretino', 'Pisello a mezza frasca aretino', 'vegetable', 'pea', 'pisello'),
  pat('tos-pisello-a-tutta-frasca-aretino', 'Pisello a tutta frasca aretino', 'vegetable', 'pea', 'pisello'),
  pat('tos-pisello-mugellano', 'Pisello mugellano', 'vegetable', 'pea', 'pisello'),
  pat('tos-pomodoro-grinzoso-sanminiatese', 'Pomodoro grinzoso sanminiatese', 'vegetable', 'tomato', 'pomodoro'),
  pat('tos-pomodoro-pallino', 'Pomodoro pallino', 'vegetable', 'tomato', 'pomodoro'),
  pat('tos-pomodoro-pendentino', 'Pomodoro pendentino', 'vegetable', 'tomato', 'pomodoro'),
  pat('tos-pomodoro-pisanello', 'Pomodoro pisanello', 'vegetable', 'tomato', 'pomodoro'),
  pat('tos-pomodoro-stella', 'Pomodoro stella', 'vegetable', 'tomato', 'pomodoro'),
  pat('tos-radicchia-di-lucca', 'Radicchia di Lucca', 'vegetable', 'chicory', 'radicchio'),
  pat('tos-scalogno-nostrale-toscano', 'Scalogno nostrale toscano', 'vegetable', 'shallot', 'scalogno'),
  pat('tos-spinacio-tipico-della-val-di-corni', 'Spinacio tipico della Val di Cornia', 'vegetable', 'spinach', 'spinacio'),
  pat('tos-uva-colombana-di-peccioli', 'Uva colombana di Peccioli', 'fruit', 'grape', 'uva'),
  pat('tos-zucchina-mora-pisana', 'Zucchina mora pisana', 'vegetable', 'courgette', 'zucchina'),
  pat('tos-zucchina-sarzanese', 'Zucchina sarzanese', 'vegetable', 'courgette', 'zucchina'),
  // ── PAT: vegetables from the regional registers ──────────────────────────
  pat('aglio-nubia', 'Aglio rosso di Nubia', 'vegetable', 'garlic', 'aglio'),
  pat('aglio-proceno', 'Aglio rosso di Proceno', 'vegetable', 'garlic', 'aglio'),
  pat('asparago-acque-albule', 'Asparago delle Acque Albule', 'vegetable', 'asparagus', 'asparago'),
  pat('broccoletto-sezze', 'Broccoletto Sezzese', 'vegetable', 'chicory', 'broccoletto'),
  pat('cappero-selargius', 'Capperi e capperoni di Selargius', 'vegetable', 'caper', 'cappero'),
  pat('carciofo-monteluponese', 'Carciofo Monteluponese', 'vegetable', 'artichoke', 'carciofo'),
  pat('carciofo-sezze', 'Carciofo di Sezze', 'vegetable', 'artichoke', 'carciofo'),
  pat('cavolfiore-fano', 'Cavolfiore Tardivo di Fano', 'vegetable', 'cauliflower', 'cavolfiore'),
  pat('cavolfiore-jesi', 'Cavolfiore Precoce di Jesi', 'vegetable', 'cauliflower', 'cavolfiore'),
  pat('cipolla-gonnosfanadiga', 'Cipolla di Gonnosfanadiga', 'vegetable', 'onion', 'cipolla'),
  pat('cipolla-nepi', 'Cipolla di Nepi', 'vegetable', 'onion', 'cipolla'),
  pat('cipolla-sermide', 'Cipolla di Sermide', 'vegetable', 'onion', 'cipolla'),
  pat('cipolla-rossa-sarda', 'Cipolla rossa', 'vegetable', 'onion', 'cipolla'),
  pat('cocomero-pontino', 'Cocomero Pontino', 'vegetable', 'watermelon', 'cocomero'),
  pat('fava-leonforte', 'Fava larga di Leonforte', 'vegetable', 'broad bean', 'fava'),
  pat('finocchio-maremma', 'Finocchio della Maremma Viterbese', 'vegetable', 'fennel', 'finocchio'),
  pat('patata-leonessa', 'Patata di Leonessa', 'vegetable', 'potato', 'patata'),
  pat('pisello-miradolo', 'Pisello di Miradolo Terme', 'vegetable', 'pea', 'pisello'),
  pat('pomodoro-fiaschetta', 'Pomodoro Fiaschetta di Fondi', 'vegetable', 'tomato', 'pomodoro'),
  pat('pomodoro-scatolone', 'Pomodoro Scatolone di Bolsena', 'vegetable', 'tomato', 'pomodoro'),
  pat('pomodoro-spagnoletta', 'Pomodoro Spagnoletta del Golfo di Gaeta', 'vegetable', 'tomato', 'pomodoro'),
  pat('radicchio-canarino', 'Radicchio canarino', 'vegetable', 'chicory', 'radicchio'),
  pat('rapa-catalogna-roccasecca', 'Rapa Catalogna di Roccasecca', 'vegetable', 'chicory', 'catalogna'),
  pat('rosa-gorizia', 'Rosa di Gorizia', 'vegetable', 'chicory', 'radicchio'),
  pat('sarzefine-zagarolo', 'Sarzefine di Zagarolo', 'vegetable', 'salsify', 'scorzonera'),
  pat('taccole-marche', 'Taccole', 'vegetable', 'pea', 'taccola'),
  pat('zucca-mantovana', 'Zucca Mantovana', 'vegetable', 'pumpkin', 'zucca'),
];
