/**
 * Cookie & privacy notice.
 *
 * This text describes the site as it is actually built. If you add analytics,
 * embeds (YouTube, Maps, a comment widget), a hosted font, or any form that
 * POSTs somewhere, this notice stops being true and the "no banner needed"
 * conclusion below stops holding — update both before shipping that change.
 *
 * Written to be read, not to be defensive: there is genuinely almost nothing
 * happening, and the honest version is short.
 */

export const legal = {
  title: 'Cookies & privacy',
  updated: 'Last updated 30 July 2026',
  intro:
    'The short version: this site sets no cookies, runs no analytics, and sends nothing about you to anyone. There is no banner to dismiss because there is nothing to consent to.',

  sections: [
    {
      heading: 'Cookies',
      body: [
        'None. This site does not set cookies — not for analytics, not for advertising, not for anything else.',
      ],
    },
    {
      heading: 'What is stored on your device',
      body: [
        'One thing, and only if you ask for it. When you use the light/dark switch in the header, your choice is saved in your browser’s local storage under the key walter-theme, so the site opens the way you left it. If you never touch the switch, nothing is written at all.',
        'That value never leaves your browser. It contains a single word — light or dark. You can delete it at any time by clearing site data for this domain, and the site will simply follow your operating system’s appearance setting again.',
        'Under the ePrivacy Directive (Article 5(3)) storage like this does not require consent: it is set only in response to something you explicitly did, it holds a display preference rather than anything identifying, and it is not used to track you. That is why there is no cookie banner.',
      ],
    },
    {
      heading: 'Third parties',
      body: [
        'None are contacted when the page loads. Fonts are served from this domain rather than a font CDN, precisely so that reading the page does not disclose your IP address to anyone else. There are no embedded videos, maps, comment widgets, social scripts, or tracking pixels.',
        'The page does contain ordinary links to GitHub, Twitch, Instagram, LinkedIn, Bandcamp and Spotify. Nothing is sent to those services unless you click a link and go there yourself, at which point their own policies apply.',
      ],
    },
    {
      heading: 'The “propose a tool” form',
      body: [
        'That form has no backend. Nothing you type is transmitted anywhere or stored on any server — when you submit it, your browser opens a draft in your own email client with the details filled in. Nothing is sent until you press send yourself, and if you close the draft, that is the end of it.',
      ],
    },
    {
      heading: 'Server logs',
      body: [
        'This site is served by Firebase Hosting, a Google service, which keeps standard web-server logs of requests — IP address, timestamp, requested file, user agent. These are generated by the act of serving a page to you, are used only to deliver the site and keep it working, and are not combined with anything else or used to build a profile.',
      ],
    },
    {
      heading: 'Your rights',
      body: [
        'Since no personal data is collected or stored here beyond the server logs described above, there is generally nothing to access, correct or delete. If you would like to ask about those logs, or anything else on this page, email say@walter.dev.',
      ],
    },
  ],

  backLabel: '← Back to the site',
} as const;
